# Generated by Django 4.2.7 on 2023-11-14 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=255, verbose_name='Nom du vendeur ou de la structure')),
                ('region', models.CharField(choices=[('Savane', 'Savane'), ('Kara', 'Kara'), ('Centrale', 'Centrale'), ('Plateaux', 'Plateaux'), ('Maritime', 'Maritime')], max_length=20, verbose_name='Région')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('status', models.CharField(choices=[('A', 'Agrégateur'), ('P', 'Producteur'), ('I', 'Intermediaire')], max_length=1, verbose_name='Statut')),
                ('unit', models.CharField(choices=[('Kg', 'Kilogramme'), ('Bol', 'Bol'), ('Ablodegbadja', 'Ablodégbadja'), ('Unite', 'Unité')], max_length=20, verbose_name='Unité')),
                ('is_product_available', models.CharField(choices=[('yes', 'Oui'), ('no', 'Non')], max_length=3, verbose_name='Produit disponible')),
                ('quantity_available', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité disponible')),
                ('quantity_to_produce', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité à produire')),
                ('availability_date', models.DateField(blank=True, null=True, verbose_name='Date de disponibilité')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketlink.productcategory', verbose_name='Catégorie de produit')),
            ],
        ),
    ]
