# Generated by Django 4.2.7 on 2023-11-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketlink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix en FCFA'),
        ),
        migrations.AlterField(
            model_name='product',
            name='email',
            field=models.EmailField(default='votre@email.com', max_length=254),
        ),
    ]
