# Generated by Django 4.2.7 on 2023-11-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketlink', '0002_product_unit_price_alter_product_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_market_available',
            field=models.BooleanField(default=False, verbose_name='Marché disponible'),
        ),
    ]
