# Generated by Django 4.2.7 on 2023-11-14 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketlink', '0003_productcategory_is_market_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketlink.productcategory', verbose_name='Catégorie de produit'),
        ),
    ]
