# Generated by Django 4.2.7 on 2023-11-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_prefecture_options_alter_region_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100, verbose_name='Nom de la ferme')),
                ('region', models.CharField(max_length=100, verbose_name='Région')),
                ('prefecture', models.CharField(max_length=100, verbose_name='Préfecture')),
                ('canton', models.CharField(max_length=100, verbose_name='Canton')),
                ('village', models.CharField(max_length=100, verbose_name='Village')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('production_type', models.CharField(max_length=100, verbose_name='Type de production')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Superficie')),
                ('current_employees', models.IntegerField(verbose_name="Nombre d'employés actuels")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('required_workers', models.IntegerField(verbose_name='Nombre de travailleurs requis')),
                ('tasks_to_perform', models.CharField(choices=[('crop_cultivation', 'Culture des plantes'), ('animal_husbandry', 'Élevage des animaux'), ('equipment_maintenance', 'Entretien des équipements')], max_length=50, verbose_name='Tâches à effectuer')),
                ('work_schedule', models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('shifts', 'Horaires variables (équipes)')], max_length=10, verbose_name='Conditions de travail')),
            ],
            options={
                'verbose_name': "Besoins en main-d'œuvre",
                'verbose_name_plural': "Besoins en main-d'œuvre",
            },
        ),
        migrations.DeleteModel(
            name='Prefecture',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
