# Generated by Django 4.2.7 on 2023-11-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(choices=[('Maritime', 'Maritime'), ('Plateaux', 'Plateaux'), ('Centrale', 'Centrale'), ('Kara', 'Kara'), ('Savanes', 'Savanes')], max_length=50, verbose_name='Région'),
        ),
    ]
