# Generated by Django 4.2.7 on 2023-11-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='area_unit',
            field=models.CharField(choices=[('m2', 'Mètre carré'), ('ha', 'Hectares'), ('lots', 'Lots (600m²)')], default='m²', max_length=10, verbose_name='Unité de superficie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.DecimalField(decimal_places=2, help_text='Entrez la valeur de la superficie', max_digits=10, verbose_name='Superficie (Valeur)'),
        ),
    ]
