# Generated by Django 4.2.7 on 2023-11-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_required_workers_alter_order_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='calendar',
            field=models.DateField(blank=True, help_text='Entrez la date du calendrier au format JJ/MM/AA', null=True, verbose_name='Calendrier'),
        ),
    ]
