# Generated by Django 4.2.7 on 2023-11-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='calendar',
        ),
    ]
